name: CI/CD Pipeline

on: push

jobs:
  build_dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'dev'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: echo "Setting up $ENVIRONMENT environment"

    - name: Install dependencies
      run: echo "Installing dependencies for $ENVIRONMENT"

    - name: Build App
      run: echo "Building app for $ENVIRONMENT environment"

    - name: Test App
      run: echo "Testing app for $ENVIRONMENT environment"

    - name: Deploy App
      run: echo "Deploying app to $ENVIRONMENT environment"

  build_qa:
    needs: build_dev
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'qa'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: echo "Setting up $ENVIRONMENT environment"

    - name: Install dependencies
      run: echo "Installing dependencies for $ENVIRONMENT"

    - name: Build App
      run: echo "Building app for $ENVIRONMENT environment"

    - name: Test App
      run: echo "Testing app for $ENVIRONMENT environment"

    - name: Deploy App
      run: echo "Deploying app to $ENVIRONMENT environment"

  build_hml:
    needs: build_qa
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'hml'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: echo "Setting up $ENVIRONMENT environment"

    - name: Install dependencies
      run: echo "Installing dependencies for $ENVIRONMENT"

    - name: Build App
      run: echo "Building app for $ENVIRONMENT environment"

    - name: Test App
      run: echo "Testing app for $ENVIRONMENT environment"

    - name: Deploy App
      run: echo "Deploying app to $ENVIRONMENT environment"

  build_prd:
    needs: build_hml
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'prd'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: echo "Setting up $ENVIRONMENT environment"

    - name: Install dependencies
      run: echo "Installing dependencies for $ENVIRONMENT"

    - name: Build App
      run: echo "Building app for $ENVIRONMENT environment"

    - name: Deploy App
      run: echo "Deploying app to $ENVIRONMENT environment"